const romeBuildings = {
  provinceCapital: {
    tier1: {
      city: {
        baseCost: 1500,
        food: 0,
        growth: 0,
        publicOrder: 0,
        latin: 0,
        political: 0,
        incomeSubsistence: 200,
        incomeAgriculture: 0,
        incomeCulture: 0,
        incomeCommerce: 0,
        incomeIndustry: 0,
        boostAll: 6,
        boostAgriculture: 0,
        boostCulture: 0,
        boostCommerce: 0,
        boostIndustry: 0
      }
    },
    tier2: {
      garrisonColonia: {
        baseCost: 2000,
        food: -1,
        growth: 3,
        publicOrder: 2,
        latin: 0,
        political: 0,
        incomeSubsistence: 250,
        incomeAgriculture: 0,
        incomeCulture: 0,
        incomeCommerce: 0,
        incomeIndustry: 0,
        boostAll: 6,
        boostAgriculture: 0,
        boostCulture: 0,
        boostCommerce: 0,
        boostIndustry: 0
      },
      civilColonia: {
        baseCost: 2700,
        food: -1,
        growth: 5,
        publicOrder: 0,
        latin: 2,
        political: 0,
        incomeSubsistence: 300,
        incomeAgriculture: 0,
        incomeCulture: 0,
        incomeCommerce: 0,
        incomeIndustry: 0,
        boostAll: 8,
        boostAgriculture: 0,
        boostCulture: 0,
        boostCommerce: 0,
        boostIndustry: 0
      }
    },
    tier3: {
      garrisonMunicipium: {
        baseCost: 3000,
        food: -4,
        growth: 3,
        publicOrder: 4,
        latin: 0,
        political: 0,
        incomeSubsistence: 300,
        incomeAgriculture: 0,
        incomeCulture: 0,
        incomeCommerce: 0,
        incomeIndustry: 0,
        boostAll: 6,
        boostAgriculture: 0,
        boostCulture: 0,
        boostCommerce: 0,
        boostIndustry: 0
      },
      civilMunicipium: {
        baseCost: 4400,
        food: -4,
        growth: 7,
        publicOrder: 0,
        latin: 4,
        political: 0,
        incomeSubsistence: 400,
        incomeAgriculture: 0,
        incomeCulture: 0,
        incomeCommerce: 0,
        incomeIndustry: 0,
        boostAll: 10,
        boostAgriculture: 0,
        boostCulture: 0,
        boostCommerce: 0,
        boostIndustry: 0
      }
    },
    tier4: {
      garrisonUrbs: {
        baseCost: 0,
        food: -8,
        growth: 3,
        publicOrder: 6,
        latin: 0,
        political: 0,
        incomeSubsistence: 350,
        incomeAgriculture: 0,
        incomeCulture: 0,
        incomeCommerce: 0,
        incomeIndustry: 0,
        boostAll: 6,
        boostAgriculture: 0,
        boostCulture: 0,
        boostCommerce: 0,
        boostIndustry: 0
      },
      civilUrbs: {
        baseCost: 0,
        food: -8,
        growth: 9,
        publicOrder: 0,
        latin: 6,
        political: 0,
        incomeSubsistence: 500,
        incomeAgriculture: 0,
        incomeCulture: 0,
        incomeCommerce: 0,
        incomeIndustry: 0,
        boostAll: 12,
        boostAgriculture: 0,
        boostCulture: 0,
        boostCommerce: 0,
        boostIndustry: 0
      }
    }
  }
}

        baseCost: 0,
        food: 0,
        growth: 0,
        publicOrder: 0,
        latin: 0,
        political: 0,
        incomeSubsistence: 0,
        incomeAgriculture: 0,
        incomeCulture: 0,
        incomeCommerce: 0,
        incomeIndustry: 0,
        boostAll: 0,
        boostAgriculture: 0,
        boostCulture: 0,
        boostCommerce: 0,
        boostIndustry: 0